/* version.c */
/* Autogenerated by Makefile - DO NOT EDIT */

#include "version.h"
const char *version_string = "1.24.5";
const char *compilation_string = "gcc -DHAVE_CONFIG_H -DSYSTEM_WGETRC=\"/usr/local/etc/wgetrc\" -DLOCALEDIR=\"/usr/local/share/locale\" -I. -I../lib -I../lib -I/opt/homebrew/Cellar/pcre2/10.43/include -I/opt/homebrew/Cellar/openssl@3/3.2.1/include -DHAVE_LIBSSL -DNDEBUG -g -O2";
const char *link_string = "gcc -I/opt/homebrew/Cellar/pcre2/10.43/include -I/opt/homebrew/Cellar/openssl@3/3.2.1/include -DHAVE_LIBSSL -DNDEBUG -g -O2 -L/opt/homebrew/Cellar/pcre2/10.43/lib -lpcre2-8 -L/opt/homebrew/Cellar/openssl@3/3.2.1/lib -lssl -lcrypto -lz ../lib/libgnu.a -liconv ";
